export const FETCH_ALL_SONGS = 'FETCH_ALL_SONGS';
export const FETCH_ALL_SONGS_BY_POPULARITY = 'FETCH_ALL_SONGS_BY_POPULARITY';
export const FETCH_ALL_SONGS_POSTED_BY_SPECIFIC_USER = 'FETCH_ALL_SONGS_POSTED_BY_SPECIFIC_USER';
export const FETCH_ALL_SONGS_BY_GENRE = 'FETCH_ALL_SONGS_BY_GENRE';
export const ADD_COMMENT_FOR_SINGLE_SONG = 'ADD_COMMENT_FOR_SINGLE_SONG';
export const POST_NEW_SONG = 'POST_NEW_SONG'

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER';

export const FETCH_ALL_GENRES = 'FETCH_ALL_GENRES';

export const FETCH_ALL_FAVORITES_BY_USER = 'FETCH_ALL_FAVORITES_BY_USER';

export const FETCH_ALL_COMMENTS_FOR_SINGLE_SONG = 'FETCH_ALL_COMMENTS_FOR_SINGLE_SONG';
export const FETCH_ALL_COMMENTS = 'FETCH_ALL_COMMENTS';

export const POST_NEW_FAVORITE = 'POST_NEW_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';
