export const FETCH_ALL_SONGS = 'FETCH_ALL_SONGS';
export const FETCH_ALL_SONGS_POSTED_BY_SPECIFIC_USER = 'FETCH_ALL_SONGS_POSTED_BY_SPECIFIC_USER';
export const FETCH_ALL_SONGS_BY_GENRE = 'FETCH_ALL_SONGS_BY_GENRE';

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_SINGLE_USER = 'FETCH_SINGLE_USER';

export const FETCH_ALL_GENRES = 'FETCH_ALL_GENRES';
