export const FETCH_ALL_SONGS = 'FETCH_ALL_SONGS';
export const FETCH_ALL_SONGS_POSTED_BY_SPECIFIC_USER = 'FETCH_ALL_SONGS_POSTED_BY_SPECIFIC_USER';
export const FETCH_ALL_SONGS_POSTED_BY_ME = 'FETCH_ALL_SONGS_POSTED_BY_ME';

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
